POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1c3N1IiwiaWQiOiI2NDQzY2IyNmQyMTNjOWIzNDM1ODk2NWYiLCJpYXQiOjE2ODIxODYyMjB9.WiIXmphTj9ybAEwZNDcz6F4pRmxIomhg9oV_IDbkJMU

{
  "title": "Kahvit",
  "author": "Clogge Bloggari",
  "url": "www.hyvatblogit.com",
  "likes": 20
}